movie_talk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("selections.urls")),
    path("admin/", admin.site.urls),
]

selections/urls.py
from django.urls import path

from . import views

app_name = "selections"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("selection/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("movies/", views.MovieIndexView.as_view(), name="movies_index"),
    path("movies/<str:slug>/", views.MovieDetailView.as_view(), name="movies_detail"),
    path("albums/", views.AlbumIndexView.as_view(), name="albums_index"),
    path("albums/<str:slug>/", views.AlbumDetailView.as_view(), name="albums_detail"),
]

movies/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Movie(models.Model):
    slug = models.CharField()
    title = models.CharField()
    director = models.CharField()
    cinematographer = models.CharField()
    writer = ArrayField(base_field=models.CharField())
    genre = ArrayField(base_field=models.CharField())
    just_watch_link = models.CharField("JustWatch Link")
    wiki_link = models.CharField("Wikipedia Link")
    imdb_link = models.CharField("IMDB Link")

    def __str__(self):
        return self.title

selections/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class Selection(models.Model):
    movie = models.ForeignKey(
        "Movie",
        on_delete=models.CASCADE,
    )
    album = models.ForeignKey(
        "Album",
        on_delete=models.CASCADE,
    )
    date = models.DateField()
    owner = models.CharField()

    def __str__(self):
        return self.get_title()

    def get_title(self):
        return f"{self.movie.title} & {self.album.title}"


class Movie(models.Model):
    slug = models.CharField()
    title = models.CharField()
    director = models.CharField()
    cinematographer = models.CharField()
    writer = ArrayField(base_field=models.CharField())
    genre = ArrayField(base_field=models.CharField())
    just_watch_link = models.CharField("JustWatch Link")
    wiki_link = models.CharField("Wikipedia Link")
    imdb_link = models.CharField("IMDB Link")

    def __str__(self):
        return self.title


class Album(models.Model):
    slug = models.CharField()
    title = models.CharField()
    artist = models.CharField()
    genres = ArrayField(base_field=models.CharField())

    def __str__(self):
        return self.title

selections/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from .models import Album, Movie, Selection


# Create your views here.


# Selection Views
class IndexView(generic.ListView):
    template_name = "selections/index.html"
    context_object_name = "list_of_selections"

    def get_queryset(self) -> QuerySet[Any]:
        return Selection.objects.order_by("date")


class DetailView(generic.DetailView):
    model = Selection
    template_name = "selections/detail.html"


# Album Views
class AlbumIndexView(generic.ListView):
    template_name = "selections/albums/index.html"
    context_object_name = "list_of_albums"

    def get_queryset(self):
        return Album.objects.order_by("title")


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = "selections/albums/detail.html"


# Movies Views
class MovieIndexView(generic.ListView):
    template_name = "selections/movies/index.html"
    context_object_name = "list_of_movies"

    def get_queryset(self):
        return Movie.objects.order_by("title")


class MovieDetailView(generic.DetailView):
    model = Movie
    template_name = "selections/movies/detail.html"

selections/templates/selections/albums/base.html
{% extends "selections/base.html" %} {% block 'body' %}
<a href="{% url 'selections:albums_index' %}">Home</a>
{% endblock %}

selections/templates/selections/albums/detail.html
{% extends 'selections/base.html' %} {% block 'content' %}
<h1>{{ album.title }}</h1>
<ul>
  <li>Artist: {{ album.artist }}</li>
  <li>Genres: {{ album.genres|join:", " }}</li>
</ul>
{% endblock %}

selections/templates/selections/albums/index.html
{% extends 'selections/base.html' %} {% block 'content' %}
<ul>
  {% for album in list_of_albums %}
  <li>
    <a href="{% url 'selections:albums_detail' album.slug %}"
      >{{ album.title }}</a
    >
  </li>
  {% endfor %}
</ul>
{% endblock %}

selections/templates/selections/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Page Title{% endblock %}</title>
  </head>
  <body>
    <div role="navigation">
      <a href="{% url 'selections:index' %}">Home</a>
      <a href="{% url 'selections:movies_index' %}">Movies</a>
      <a href="{% url 'selections:albums_index' %}">Albums</a>
    </div>
    {% block 'content' %}{% endblock %}
  </body>
</html>

selections/templates/selections/detail.html
{% extends 'selections/base.html' %} {% block 'content'%}
<h1>{{ selection.movie.title }} &amp; {{ selection.album.title }}</h1>
<ul>
  <li>
    Movie:
    <a href="{% url 'selections:movies_detail' selection.movie.slug %}"
      >{{ selection.movie.title }}</a
    >
  </li>
  <li>
    Album:
    <a href="{% url 'selections:albums_detail' selection.album.slug %}"
      >{{ selection.album.title }}</a
    >
  </li>
</ul>
{% endblock %}

selections/templates/selections/index.html
{% extends 'selections/base.html' %} {% block 'content' %}
<ul>
  {% for selection in list_of_selections %}
  <li>
    <a href="{% url 'selections:detail' selection.id %}"
      >{{ selection.movie.title }} &amp; {{ selection.album.title }}</a
    >
  </li>
  {% endfor %}
</ul>
{% endblock %}

selections/templates/selections/movies/base.html
<a href="{% url 'selections:movies_index' %}">Home</a>
<body>
  {% block 'body' %} {% endblock %}
</body>

selections/templates/selections/movies/detail.html
{% extends 'selections/base.html' %} {% block 'content' %}
<h1>{{ movie.title }}</h1>
<ul>
  <li>Director by: {{ movie.director }}</li>
  <li>Cinematography by: {{ movie.cinematographer }}</li>
  <li>Written by: {{ movie.writer|join:", "}}</li>
  <li>Genres: {{ movie.genre|join:", "}}</li>
</ul>
<h2>Links</h2>
<ul>
  <li><a href="{{ movie.just_watch_link }}">JustWatch</a></li>
  <li><a href="{{ movie.wiki_link }}">Wikipedia</a></li>
  <li><a href="{{ movie.imdb_link }}">IMDB</a></li>
</ul>
{% endblock %}

selections/templates/selections/movies/index.html
{% extends 'selections/base.html' %} {% block 'content' %}
<ul>
  {% for movie in list_of_movies %}
  <li>
    <a href="{% url 'selections:movies_detail' movie.slug %}"
      >{{ movie.title }}</a
    >
  </li>
  {% endfor %}
</ul>
{% endblock %}